import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // bookSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Physical AI & Humanoid Robotics Book',
  //     items: [
  //       'preface',
  //       'chapter1-intro-physical-ai',
  //       'chapter2-embodied-intelligence',
  //       'chapter3-humanoid-basics',
  //       'chapter4-ros2-control',
  //       'chapter5-simulation',
  //       'chapter6-isaac-digital-twins',
  //       'chapter7-vla-models',
  //       'chapter8-deploy-humanoids',
  //       'glossary',
  //       'index-book',
  //     ],
  //   },
  // ],
};

module.exports=sidebars;


